### ISSUE TITLE
Exclude filename extension from the sync

### ISSUE THREAD

**Issue by SirTerrific** [Fitus/Zaloha.sh#2]
Hi,

I tried --findSourceOps='-name nfo -prune -o' and --findSourceOps='-name NFO -prune -o' but without success
or
--findSourceOps='-name *.nfo -prune -o' and --findSourceOps='-name *.NFO -prune -o' but without success

Thanks.
Jerome CARBEL

**Comment by Fitus** [comment]
Hi,

let's construct the exclusion of the .NFO files step by step to see where the problem occurs:

First, let's produce a test case:

```bash
$ mkdir test_source
$ touch test_source/file.txt
$ touch test_source/file.nfo
$ touch test_source/file.NFO
$ mkdir test_source/subdir.nfo
$ touch test_source/subdir.nfo/subfile.txt
$ mkdir test_backup
```

Now, let's test with FIND:

```bash
$ find test_source/ -name '*.nfo' -prune -o -name '*.NFO' -prune -o -printf '%P\n'

file.txt
```

Now, let's test with Zaloha (I use options --noProgress and --noLastRun to suppress screen outputs which are irrelevant for this investigation):

```bash
$ ./Zaloha.sh --sourceDir='test_source' --backupDir='test_backup' --findSourceOps='-name *.nfo -prune -o -name *.NFO -prune -o' --noProgress --noLastRun

TO BE COPIED TO ./test_backup/
===========================================
NEW       file.txt

Execute above listed copies to ./test_backup/ ? [Y/y=Yes, other=do nothing and abort]: n
Zaloha.sh: User requested Zaloha to abort
```

Looks good. Now, if you want to exclude only files with .NFO suffix but not eventual directories with such suffix, let's make the FIND options more precise and test again with FIND:

```bash
$ find test_source/ '(' -type f -a -name '*.nfo' ')' -prune -o '(' -type f -a -name '*.NFO' ')' -prune -o -printf '%P\n'

file.txt
subdir.nfo
subdir.nfo/subfile.txt
```

Looks good. If we now exclude only files, the -prune operand is not needed anymore, as there is nothing "below a file":

```bash
$ find test_source/ '(' -type f -a -name '*.nfo' ')' -o '(' -type f -a -name '*.NFO' ')' -o -printf '%P\n'

file.txt
subdir.nfo
subdir.nfo/subfile.txt
```

Let's now make a final test with Zaloha:

```bash
$ ./Zaloha.sh --sourceDir='test_source' --backupDir='test_backup' --findSourceOps='( -type f -a -name *.nfo ) -o ( -type f -a -name *.NFO ) -o' --noProgress --noLastRun

TO BE COPIED TO ./test_backup/
===========================================
NEW       file.txt
MKDIR     subdir.nfo
NEW       subdir.nfo/subfile.txt

Execute above listed copies to ./test_backup/ ? [Y/y=Yes, other=do nothing and abort]: n
Zaloha.sh: User requested Zaloha to abort
```

Also all looks good. Can you please re-play the above steps on your system to find out where the problems steps in? We might again have a case where a Unix command (now FIND) behaves differently on different systems ...

Let me know the outcome. Thanks

F.

**Comment by SirTerrific** [comment]
HI,

All worked well. 

Debian 10

zaloha.sh --sourceDir='test_source' --backupDir='test_backup' --findSourceOps='-name *.nfo -prune -o -name *.NFO -prune -o' --noProgress --noLastRun

TO BE COPIED TO ./test_backup/
===========================================
NEW       file.txt

Execute above listed copies to ./test_backup/ ? [Y/y=Yes, other=do nothing and abort]:
Zaloha.sh: User requested Zaloha to abort

find test_source/ '(' -type f -a -name '*.nfo' ')' -prune -o '(' -type f -a -name '*.NFO' ')' -prune -o -printf '%P\n'

subdir.nfo
subdir.nfo/subfile.txt
file.txt
root@Oden:/opt/app/test# find test_source/ '(' -type f -a -name '*.nfo' ')' -o '(' -type f -a -name '*.NFO' ')' -o -printf '%P\n'

subdir.nfo
subdir.nfo/subfile.txt
file.txt
zaloha.sh --sourceDir='test_source' --backupDir='test_backup' --findSourceOps='( -type f -a -name *.nfo ) -o ( -type f -a -name *.NFO ) -o' --noProgress --noLastRun

TO BE COPIED TO ./test_backup/
===========================================
NEW       file.txt
MKDIR     subdir.nfo
NEW       subdir.nfo/subfile.txt

Execute above listed copies to ./test_backup/ ? [Y/y=Yes, other=do nothing and abort]:
Zaloha.sh: User requested Zaloha to abort
